import "./globals.css";
import { NextAuthProvider } from "@/contexts/nextAuthProvider";
import { option } from "@/libs/authOption";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import type { JSX, ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

const RootLayout = async ({ children }: { children: ReactNode }): Promise<JSX.Element> => {
  const session = await getServerSession(option);
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>{children}</NextAuthProvider>
      </body>
    </html>
  );
};

// biome-ignore lint/style/noDefaultExport: <explanation>
export default RootLayout;
